[project]
name = "dps-gaussian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.6.0",
    "matplotlib>=3.10.1",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
